default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sns_development


test:
  <<: *default
  database: sns_test


production:
  <<: *default
  database: sns_production
  username: sns
  password: <%= ENV['SNS_DATABASE_PASSWORD'] %>
